services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
  postgres_test:
    image: postgres
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_TEST_PASSWORD}"
      POSTGRES_USER: "${DB_TEST_USER}"
      POSTGRES_DB: "${DB_TEST_NAME}"
    ports:
      - "5433:5432"
  app:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    environment:
      APP_ENV: development
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "postgres"
      DB_TEST_PASSWORD: "${DB_TEST_PASSWORD}"
      DB_TEST_USER: "${DB_TEST_USER}"
      DB_TEST_NAME: "${DB_TEST_NAME}"
      DB_TEST_HOST: "postgres_test"
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: {}
  pgdata_test: {}
