services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
  app:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    environment:
      APP_ENV: development
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "postgres"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: {}
