basePath: /api
definitions:
  request.NewTransactionRequest:
    properties:
      account_id:
        type: string
      amount:
        type: number
      operation_type_id:
        type: integer
    required:
    - account_id
    - amount
    - operation_type_id
    type: object
  request.UserAccountRequest:
    properties:
      document_number:
        type: string
    required:
    - document_number
    type: object
  response.NewTransactionResponse:
    properties:
      account_id:
        type: string
      amount:
        type: number
      operation_type_id:
        type: integer
      transaction_id:
        type: string
    type: object
  response.UserAccountResponse:
    properties:
      account_id:
        type: string
      document_number:
        type: string
    type: object
info:
  contact: {}
  description: A transaction management software API in go using Gin-Framework
  title: Accounts API
  version: "1.0"
paths:
  /v1/accounts:
    post:
      description: Save a new user in DB
      parameters:
      - description: Create user account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/request.UserAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserAccountResponse'
      summary: Create a new user account
      tags:
      - accounts
  /v1/accounts/{id}:
    get:
      description: Get the user account stored in DB
      parameters:
      - description: get account by id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserAccountResponse'
      summary: Get user's account
      tags:
      - accounts
  /v1/transactions:
    post:
      description: Save a new user in DB
      parameters:
      - description: Create trasaction for a given user
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/request.NewTransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.NewTransactionResponse'
      summary: Create a new user transaction
      tags:
      - transactions
swagger: "2.0"
